# database
master:
  image: registry.cn-hangzhou.aliyuncs.com/flash20/mysql:5.7
  ports:
    - "3317:3306"
  volumes:
    - ./5.7/run.sh:/docker-entrypoint-initdb.d/run.sh
  volumes_from:
    - data-master
  environment:
    - REPLICATION_MASTER=true
    - MYSQL_ROOT_PASSWORD=123456
    - SERVER_ID=1
  restart: always
  #privileged: true
slave:
  image: registry.cn-hangzhou.aliyuncs.com/flash20/mysql:5.7
  ports:
    - "3318:3306"
  volumes:
    - ./5.7/run.sh:/docker-entrypoint-initdb.d/run.sh
  volumes_from:
    - data-slave
  links:
    - master:mysql
  environment:
    - REPLICATION_SLAVE=true
    - MYSQL_ROOT_PASSWORD=123456
    - SERVER_ID=2
  restart: always
  #privileged: true
data-master:
  image: tutum/ubuntu:latest
  volumes:
     - /var/lib/mysql
  restart: always
data-slave:
  image: tutum/ubuntu:latest
  volumes:
     - /var/lib/mysql
  restart: always